# chat-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: manavendrasen/scalable-chat-app 
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi

---
# chat-app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080 
  selector:
    app: chat-app